### ISSUE TITLE
Do you have any plans to migrate it to WebExtension APIs?

### ISSUE THREAD

**Issue by thanos-massias** [sunnygoyal/scienfic-calculator#12]
First of all thanks for the Scientific Calculator addon. I've been using it for years and really like it. 

Do you have any plans to migrate it to WebExtension APIs?

**Comment by Ede123** [comment]
I'm afraid this is very unlikely at this time:
* While it might be possible to port somehow, the whole UI part would need to be completely rewritten and - as it's the sad case with all web-extensions - will probably still be inferior afterwards. This is a lot of work for which at least I currently do not have the time.
* Even if I had the time I'm lacking the motivation to put in any work geared towards Firefox right now: Mozilla ruthlessly breaking all existing extensions on purpose and removing customization possibilities with every new version of Firefox made me loose trust in the foundation and the browser itself - I'm not willing to spend my spare time on a project that has set a course that goes against everything Firefox once stood for.

**Comment by thanos-massias** [comment]
Dear Eduard, thank you for your response. I understand the frustration over these Firefox changes.
In any case, thanks again for all the work you have put into making that addon.
