### ISSUE TITLE
error with % sign

### ISSUE THREAD

**Issue by NSP-0123456** [sunnygoyal/scienfic-calculator#15]
i would like to use % as percent operator but each time i use it i get invalid expression and it is not possible to define it as operator.... using ff 56.02 64bit Scientific Calculator 5.4.1

**Comment by Ede123** [comment]
The current implementation requires the percent operator to be used in an expression and it will operate on the expression block to the left, e.g.
* "100+10%" should work and return 110
* "100+10%*2" will be evaluated as "(100+10%)*2" and return 220
* "10%*2" is an error as there's nothing left of the "10%".

**Comment by NSP-0123456** [comment]
Great it work as you described !
I'm more used to have either 10% directly transformed  to 0.1 or /* % */ ( X,Y) defined as X*Y/100 but no fancy backtrack.
