### ISSUE TITLE
Bootstrapped extension

### ISSUE THREAD

**Issue by yfdyh000** [sunnygoyal/scienfic-calculator#8]
https://developer.mozilla.org/en-US/Add-ons/Bootstrapped_extensions
This may be difficult, but it will be better.

Or, we can wait the https://wiki.mozilla.org/WebExtensions.

**Comment by Ede123** [comment]
Sorry, not gonna happen... I'm the only active developer right now and I have barely enough time to maintain the extension, let alone a complete rewrite.

Actually with the announcement of WebExtensions (and moreover the discontinuation of XUL/XPCOM based add-ons that comes along with it) the future of Scientific Calculator is more than uncertain. I don't know if I'll be able (and willing) to invest the time that's needed for a rewrite that might be compatible with WebExtensions.

**Comment by yfdyh000** [comment]
Yes, it is a reminder / enhancement instead of a feature request. I fully understand.
